### ISSUE TITLE
US 13 - Navigation Bar

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Solar-Calculator-Capstone-Project#32]
## Value proposition

As a user
I want to see and use a navigation bar
in order to move to different pages

## Description
![Image](https://github.com/sirtobiwan/Solar-Calculator-Capstone-Project/assets/125971942/6e0704ba-1032-494d-810a-bd28d240c7c3)

## Acceptance criteria

- [ ] display navigation bar
- [ ] be able to move to different pages with the navigation bar

## Tasks

- [ ] create new branch
- [ ] create new component
- [ ] add navigation bar with routing to different pages
