### ISSUE TITLE
US-14 - Testing/Button

### ISSUE THREAD

**Issue by sirtobiwan** [sirtobiwan/Solar-Calculator-Capstone-Project#34]
## Value proposition

As a user
I want to to click the button "next"
in order to move to the next page

## Description
<img width="171" alt="Bildschirm­foto 2023-05-22 um 13 08 52" src="https://github.com/sirtobiwan/Solar-Calculator-Capstone-Project/assets/125971942/8a47d957-9ca4-4c08-99c5-31041c001310">

## Acceptance criteria

- [ ] click on button next 
- [ ] move to next page

## Tasks

- [ ] create new branch
- [ ] create new testing file
- [ ] install jest
- [ ] test if prop of text and href will be rendered
